# -*- coding: utf-8 -*-
"""cv lab 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oog5p-b2xutrWFHC3dUeXKj9ypXaia7m
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

#load the image in grayscale
#replace 'input_image.jpg'with yourfile name
img=cv2.imread('/content/img 2',cv2.IMREAD_GRAYSCALE)

#check if image loaded successfully
if img is None:
  print('Error loading image')
else:
  #set up the plot figure
  plt.figure(figsize=(15,10)) # Increased figure size for better display with 3x3 grid

  #display original image
  plt.subplot(3,3,1) # Changed to 3x3 grid, position 1
  plt.imshow(img,cmap='gray')
  plt.title('Original Image')
  plt.axis('off')

  #loop through all 8 bit planes
  for i in range(8):
     #extract  the i-th bit plane
     #shift bits rightby 'i' and perform  bitwise AND with
     bit_plane=(img>>i) & 1 # Added parenthesis for clarity and correctness in bitwise operation

     #scale  to 0-255 for visualization (0 becomes black, 1 becomes white)
     vis_plane =bit_plane *255

     #plotting
     plt.subplot(3,3,i+2) # Changed to 3x3 grid, positions 2 to 9
     plt.imshow(vis_plane,cmap='gray')
     plt.title(f'Bit Plane {i}')
     plt.axis('off')

  plt.tight_layout()
  plt.show()